---
name: Test-Ping
version: 0.12
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
abstract: Testing pings using Net::Ping
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/xsawyerx/test-ping
build_requires:
  Test::More: 0
  Test::Timer: 0.05
requires:
  Carp: 0
  Net::Ping: 2.33
  Test::Builder: 0.86
  Tie::Scalar: 0
configure_requires:
  Module::Build: 0.35
provides:
  Test::Ping:
    file: lib/Test/Ping.pm
    version: 0.12
  Test::Ping::Ties::BIND:
    file: lib/Test/Ping/Ties/BIND.pm
    version: 0.01
  Test::Ping::Ties::HIRES:
    file: lib/Test/Ping/Ties/HIRES.pm
    version: 0.01
  Test::Ping::Ties::PORT:
    file: lib/Test/Ping/Ties/PORT.pm
    version: 0.01
  Test::Ping::Ties::PROTO:
    file: lib/Test/Ping/Ties/PROTO.pm
    version: 0.04
  Test::Ping::Ties::SERVICE_CHECK:
    file: lib/Test/Ping/Ties/SERVICE_CHECK.pm
    version: 0.01
  Test::Ping::Ties::SOURCE_VERIFY:
    file: lib/Test/Ping/Ties/SOURCE_VERIFY.pm
    version: 0.01
  Test::Ping::Ties::TIMEOUT:
    file: lib/Test/Ping/Ties/TIMEOUT.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
